import { DataSource } from 'typeorm';
import { DataSource as DataSourceEntity, DataSourceType, DataSourceStatus } from '../entities';

export async function seedDataSources(dataSource: DataSource) {
  const dataSourceRepository = dataSource.getRepository(DataSourceEntity);

  const dataSources = [
    // Fundamental Analysis Sources
    {
      name: 'Fundamentei',
      code: 'fundamentei',
      url: 'https://fundamentei.com',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de fundamentos',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'Investidor10',
      code: 'investidor10',
      url: 'https://investidor10.com.br',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de fundamentos',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'Status Invest',
      code: 'statusinvest',
      url: 'https://statusinvest.com.br',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de fundamentos',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'Fundamentus',
      code: 'fundamentus',
      url: 'https://www.fundamentus.com.br',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de fundamentos',
      requiresLogin: false,
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'Investsite',
      code: 'investsite',
      url: 'https://www.investsite.com.br',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de fundamentos',
      requiresLogin: false,
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.85,
    },
    {
      name: 'BRAPI',
      code: 'brapi',
      url: 'https://brapi.dev',
      type: DataSourceType.FUNDAMENTAL,
      status: DataSourceStatus.ACTIVE,
      description: 'API de dados de ações brasileiras',
      requiresLogin: false,
      loginType: 'token',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },

    // General Market Analysis Sources
    {
      name: 'Investing.com Brasil',
      code: 'investing',
      url: 'https://br.investing.com',
      type: DataSourceType.GENERAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise geral do mercado',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'ADVFN Brasil',
      code: 'advfn',
      url: 'https://br.advfn.com',
      type: DataSourceType.GENERAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise geral do mercado',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.85,
    },
    {
      name: 'Google Finance',
      code: 'google_finance',
      url: 'https://www.google.com/finance',
      type: DataSourceType.GENERAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Dados financeiros do Google',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },

    // Technical Analysis Sources
    {
      name: 'TradingView',
      code: 'tradingview',
      url: 'https://br.tradingview.com',
      type: DataSourceType.TECHNICAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise técnica e gráfica',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },

    // Options Analysis Sources
    {
      name: 'Opções.net.br',
      code: 'opcoes',
      url: 'https://opcoes.net.br',
      type: DataSourceType.OPTIONS,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de opções',
      requiresLogin: true,
      loginType: 'credentials',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },

    // Insider Analysis Sources
    {
      name: 'Griffin',
      code: 'griffin',
      url: 'https://griffin.app.br',
      type: DataSourceType.INSIDER,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise de insiders',
      requiresLogin: false,
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.85,
    },

    // Institutional Reports Sources
    {
      name: 'BTG Pactual Research',
      code: 'btg',
      url: 'https://content.btgpactual.com/research',
      type: DataSourceType.REPORT,
      status: DataSourceStatus.ACTIVE,
      description: 'Relatórios institucionais BTG',
      requiresLogin: true,
      loginType: 'token',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'XPI Research',
      code: 'xpi',
      url: 'https://conteudos.xpi.com.br',
      type: DataSourceType.REPORT,
      status: DataSourceStatus.ACTIVE,
      description: 'Relatórios institucionais XPI',
      requiresLogin: true,
      loginType: 'token',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },

    // News Sources
    {
      name: 'Google News',
      code: 'google_news',
      url: 'https://news.google.com',
      type: DataSourceType.NEWS,
      status: DataSourceStatus.ACTIVE,
      description: 'Notícias gerais',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'Bloomberg Línea',
      code: 'bloomberg',
      url: 'https://www.bloomberglinea.com.br',
      type: DataSourceType.NEWS,
      status: DataSourceStatus.ACTIVE,
      description: 'Notícias financeiras',
      requiresLogin: false,
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'Valor Econômico',
      code: 'valor',
      url: 'https://valor.globo.com',
      type: DataSourceType.NEWS,
      status: DataSourceStatus.ACTIVE,
      description: 'Notícias financeiras',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.95,
    },
    {
      name: 'InfoMoney',
      code: 'infomoney',
      url: 'https://www.infomoney.com.br',
      type: DataSourceType.NEWS,
      status: DataSourceStatus.ACTIVE,
      description: 'Notícias financeiras',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },

    // AI Sources
    {
      name: 'ChatGPT',
      code: 'chatgpt',
      url: 'https://chatgpt.com',
      type: DataSourceType.AI,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise com IA - ChatGPT',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'DeepSeek',
      code: 'deepseek',
      url: 'https://www.deepseek.com',
      type: DataSourceType.AI,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise com IA - DeepSeek',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.85,
    },
    {
      name: 'Gemini',
      code: 'gemini',
      url: 'https://gemini.google.com/app',
      type: DataSourceType.AI,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise com IA - Gemini',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'Claude',
      code: 'claude',
      url: 'https://claude.ai/new',
      type: DataSourceType.AI,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise com IA - Claude',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.9,
    },
    {
      name: 'Grok',
      code: 'grok',
      url: 'https://grok.com',
      type: DataSourceType.AI,
      status: DataSourceStatus.ACTIVE,
      description: 'Análise com IA - Grok',
      requiresLogin: true,
      loginType: 'google',
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 0.85,
    },

    // Official Data Sources
    {
      name: 'B3',
      code: 'b3',
      url: 'https://www.b3.com.br',
      type: DataSourceType.GENERAL,
      status: DataSourceStatus.ACTIVE,
      description: 'Dados oficiais da B3',
      requiresLogin: false,
      isVerified: true,
      isTrusted: true,
      reliabilityScore: 1.0,
    },
  ];

  for (const sourceData of dataSources) {
    const existing = await dataSourceRepository.findOne({
      where: { code: sourceData.code },
    });

    if (!existing) {
      const source = dataSourceRepository.create(sourceData);
      await dataSourceRepository.save(source);
      console.log(`Created data source: ${sourceData.name}`);
    } else {
      console.log(`Data source already exists: ${sourceData.name}`);
    }
  }

  console.log('Data sources seeding completed!');
}
